Fix win32 utf8 encoding bug
A bug in the win32 iconv library in FreeTDS caused problems with certain
unicode codepoints:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pymssql.pyx", line 515, in pymssql.Cursor.fetchall (pymssql.c:8022)
  File "pymssql.pyx", line 467, in pymssql.Cursor.getrow (pymssql.c:7035)
  File "_mssql.pyx", line 418, in _mssql.MSSQLRowIterator.__next__ (_mssql.c:4317)
  File "_mssql.pyx", line 1069, in _mssql.MSSQLConnection.fetch_next_row (_mssql.c:10650)
  File "_mssql.pyx", line 1235, in _mssql.MSSQLConnection.get_row (_mssql.c:12131)
  File "_mssql.pyx", line 758, in _mssql.MSSQLConnection.convert_db_value (_mssql.c:7762)
  File "C:\programs\Python26\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 10-11: invalid continuation byte